name: Coverity Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest

    env:
      BRIDGE_COVERITY_CONNECT_URL: ${{ secrets.BRIDGE_COVERITY_CONNECT_URL }}
      BRIDGE_COVERITY_CONNECT_USER_NAME: ${{ secrets.BRIDGE_COVERITY_CONNECT_USER_NAME }}
      BRIDGE_COVERITY_CONNECT_USER_PASSWORD: ${{ secrets.BRIDGE_COVERITY_CONNECT_USER_PASSWORD }}

      BRIDGE_COVERITY_BUILD_COMMAND: "./mvnw clean package"

      NODE_TLS_REJECT_UNAUTHORIZED: "0"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - run: chmod +x mvnw

      - name: Install Coverity Certificate
        env:
          COVERITY_CERT: ${{ secrets.COVERITY_CERT }}
        run: |
          echo "$COVERITY_CERT" > coverity.crt
          sudo cp coverity.crt /usr/local/share/ca-certificates/coverity.crt
          sudo update-ca-certificates || true

      - name: Test Coverity Connectivity
        run: |
          curl -kv $BRIDGE_COVERITY_CONNECT_URL || true

      - name: Download Bridge CLI
        run: |
          curl -fLsS -o bridge.zip "https://repo.blackduck.com/artifactory/bds-integrations-release/com/blackduck/integration/bridge/binaries/bridge-cli-bundle/latest/bridge-cli-bundle-linux64.zip"
          unzip -qo bridge.zip

      - name: Run Bridge Scan
        run: |
          ./bridge-cli-bundle-linux64/bridge-cli \
            --stage connect \
            coverity.connect.project.name="WebGoat-GitHub25" \
            coverity.connect.stream.name="WebGoat-Github-main25"
