name: Coverity Scan 22.34

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  coverity:
    runs-on: ubuntu-latest

    env:
      BRIDGE_COVERITY_CONNECT_URL: ${{ secrets.BRIDGE_COVERITY_CONNECT_URL }}
      BRIDGE_COVERITY_CONNECT_USER_NAME: ${{ secrets.BRIDGE_COVERITY_CONNECT_USER_NAME }}
      BRIDGE_COVERITY_CONNECT_USER_PASSWORD: ${{ secrets.BRIDGE_COVERITY_CONNECT_USER_PASSWORD }}

      BRIDGE_COVERITY_BUILD_COMMAND: "./mvnw -e -X clean package -DskipTests"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Make Maven executable
        run: chmod +x mvnw

      - name: Download Bridge
        run: |
          curl -fLsS -o bridge.zip "https://repo.blackduck.com/artifactory/bds-integrations-release/com/blackduck/integration/bridge/binaries/bridge-cli-bundle/latest/bridge-cli-bundle-linux64.zip"
          unzip -qo bridge.zip

      - name: Run Coverity Scan
        run: |
          ./bridge-cli-bundle-linux64/bridge-cli \
            --stage connect \
            coverity.connect.project.name="WebGoat-GitHub252" \
            coverity.connect.stream.name="WebGoat-Github-main252"
